import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import Navbar from "@/components/NavigationComponents/Navbar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "Print Plus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className="font-alex overflow-hidden-x-hidden">
        <AppRouterCacheProvider>
          <Navbar />
          {children}
          <ToastContainer position="top-right" autoClose={3000} />
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
